services:
  - type: web
    name: takeoff-api
    env: docker
    plan: free       # upgrade later for heavier inference
    region: oregon
    dockerfilePath: backend/Dockerfile
    healthCheckPath: /docs
    autoDeploy: true
    envVars:
      - key: MODEL_PATH
        value: /app/models/light_yolov8.pt
      - key: UVICORN_PORT      # Render injects PORT; just pass it through
        fromService: takeoff-api
